### ISSUE TITLE
Display the list of detected names

### ISSUE THREAD

**Issue by ThibaultVlacich** [ajdavis/twitter-gender-distribution#37]
Hello,

I tested this app on my own Twitter account, and it seems like there's A LOT of incorrect detections (for me at least). A lot of the women I follow are detected as "no gender, unknown" because they have a unisex name (Shannon, Lindsay, Ashley... for example), some are even detected as "male".
Weirdly, I did not notice that much incorrect detections for men.

I understand that it's not really an issue, it's working as expected since it's how the names are labelled in the source lib, but I think it would be best to be able to see exactly what names have been detected and to which category they have been assigned, to be able to properly understand the result, not just numbers that don't really mean anything and are probably incorrect for a bunch of people.

I'm open to try to work on a PR if you're interested in that feature.

**Comment by ajdavis** [comment]
Hello. My goal is to encourage users to follow more women and nonbinary people on Twitter.

I don't think it's a good idea to display hundreds of people's names and their guessed gender. Right now, proporti.onl tries to show the important information: an estimate of the number of male/female/nonbinary people among your friends, followers, and recent timeline posts. It's inaccurate, of course, and you can see it's inaccurate because it shows you how many people are "no gender, unknown". The *details* of its inaccuracy are not very important in my opinion: my goal is to encourage users to follow more women and nonbinary people, not to encourage them to check proporti.onl's accuracy at guessing individual people's genders by their first names.

Do you think that if proporti.onl showed a list of hundreds of people's names and guessed genders, that there would be anything useful you could do with that information?

**Comment by ThibaultVlacich** [comment]
Your goal is to make people follow more women by showing them inaccurate data to make them think that they don’t follow enough women / make the feel bad, am I understanding correctly? Your app tells me I follow <20% women, but my hand-made count says 55%.

Dumbest take I ever read, sorry.

**Comment by ajdavis** [comment]
You have deliberately misinterpreted my response. I'm deleting this conversation.
